use super::*;

/// Supported shell targets for generated integration scripts.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum ShellKind {
    Bash,
}

/// Renders shell integration that wires configured navigation and completion into the shell.
pub(super) fn shell_init_script(shell: ShellKind, config: &ShellConfig) -> String {
    match shell {
        ShellKind::Bash => bash_init_script(config),
    }
}

fn bash_init_script(config: &ShellConfig) -> String {
    let mut script = bash_cli_completion_script();

    if let Some(command) = config.navigation_command() {
        if !script.ends_with('\n') {
            script.push('\n');
        }
        script.push('\n');
        if config.zoxide == ShellZoxideMode::Auto {
            script.push_str(&bash_navigation_script_with_zoxide(command));
        } else {
            script.push_str(&bash_navigation_script_without_zoxide(command));
        }
    }

    script
}

fn bash_cli_completion_script() -> String {
    let mut command = cli();
    let mut output = Vec::new();
    clap_complete::generate(clap_complete::Shell::Bash, &mut command, "jx", &mut output);
    let mut script = String::from_utf8(output).expect("clap_complete emits valid UTF-8");
    script.push_str(bash_project_argument_completion_script());
    script
}

fn bash_project_argument_completion_script() -> &'static str {
    r#"
# Generated by jx shell init bash: project argument completion.
__jx_project_arg_completion() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local command=""
  local previous=""
  local word
  local positional_count=0
  local all_selected=0

  for (( i = 1; i < COMP_CWORD; i++ )); do
    word="${COMP_WORDS[i]}"
    if [[ -z "$command" ]]; then
      case "$word" in
        remote-status|rs|fetch|f|sync|open|o) command="$word" ;;
      esac
      continue
    fi

    case "$previous" in
      --repo)
        previous=""
        (( positional_count++ ))
        continue
        ;;
      --jobs|-j)
        previous=""
        continue
        ;;
    esac

    case "$word" in
      -a|--all) [[ "$command" != "open" && "$command" != "o" ]] && all_selected=1 ;;
      --repo=*|--jobs=*) ;;
      -*) previous="$word" ;;
      prs|pull-requests)
        if [[ ( "$command" == "open" || "$command" == "o" ) && $positional_count -eq 0 ]]; then
          :
        else
          (( positional_count++ ))
        fi
        ;;
      *) (( positional_count++ )) ;;
    esac
  done

  case "$previous" in
    --repo)
      local IFS=$'\n'
      COMPREPLY=($(compgen -W "$(command jx work complete --repositories --prefix "$cur" 2>/dev/null)" -- "$cur"))
      return
      ;;
    --jobs|-j)
      _jx "$@"
      return
      ;;
  esac

  if [[ -n "$command" && "$cur" != -* && $positional_count -eq 0 && $all_selected -eq 0 ]]; then
    local IFS=$'\n'
    COMPREPLY=($(compgen -W "$(command jx work complete --repositories --prefix "$cur" 2>/dev/null)" -- "$cur"))
  else
    _jx "$@"
  fi
}

complete -F __jx_project_arg_completion jx
"#
}

fn bash_navigation_script_with_zoxide(command: &str) -> String {
    let helper_prefix = helper_prefix(command);
    format!(
        r#"# Generated by jx shell init bash.
{helper_prefix}_zoxide_enabled() {{
  command -v zoxide >/dev/null 2>&1
}}

{command}() {{
  local target ret

  if (( $# == 0 )); then
    target="$HOME"
  elif (( $# == 1 )) && target="$(command jx work root "$1" 2>/dev/null)"; then
    :
  elif {helper_prefix}_zoxide_enabled && target="$(zoxide query "$@" 2>/dev/null)"; then
    :
  else
    pushd "$@" > /dev/null
    ret=$?
    (( ret == 0 )) && dirs -v
    return $ret
  fi

  pushd "$target" > /dev/null
  ret=$?
  (( ret == 0 )) && dirs -v
  return $ret
}}

{helper_prefix}_completion() {{
  local cur="${{COMP_WORDS[COMP_CWORD]}}"
  local IFS=$'\n'
  local candidates=()
  local candidate existing duplicate path

  while IFS= read -r candidate; do
    [[ -n "$candidate" ]] || continue
    duplicate=0
    for existing in "${{candidates[@]}}"; do
      [[ "$existing" == "$candidate" ]] && duplicate=1 && break
    done
    (( duplicate == 0 )) && candidates+=("$candidate")
  done < <(command jx work complete --prefix "$cur" 2>/dev/null)

  if {helper_prefix}_zoxide_enabled; then
    while IFS= read -r path; do
      candidate="$(basename "$path")"
      [[ -n "$candidate" ]] || continue
      duplicate=0
      for existing in "${{candidates[@]}}"; do
        [[ "$existing" == "$candidate" ]] && duplicate=1 && break
      done
      (( duplicate == 0 )) && candidates+=("$candidate")
    done < <(zoxide query --list "$cur" 2>/dev/null)
  fi

  COMPREPLY=($(compgen -W "${{candidates[*]}}" -- "$cur"))
}}

complete -o nospace -F {helper_prefix}_completion {command}
"#
    )
}

fn bash_navigation_script_without_zoxide(command: &str) -> String {
    let helper_prefix = helper_prefix(command);
    format!(
        r#"# Generated by jx shell init bash.
{command}() {{
  local target ret

  if (( $# == 0 )); then
    target="$HOME"
  elif (( $# == 1 )) && target="$(command jx work root "$1" 2>/dev/null)"; then
    :
  else
    pushd "$@" > /dev/null
    ret=$?
    (( ret == 0 )) && dirs -v
    return $ret
  fi

  pushd "$target" > /dev/null
  ret=$?
  (( ret == 0 )) && dirs -v
  return $ret
}}

{helper_prefix}_completion() {{
  local cur="${{COMP_WORDS[COMP_CWORD]}}"
  local IFS=$'\n'
  local candidates=()
  local candidate

  while IFS= read -r candidate; do
    [[ -n "$candidate" ]] && candidates+=("$candidate")
  done < <(command jx work complete --prefix "$cur" 2>/dev/null)

  COMPREPLY=($(compgen -W "${{candidates[*]}}" -- "$cur"))
}}

complete -o nospace -F {helper_prefix}_completion {command}
"#
    )
}

fn helper_prefix(command: &str) -> String {
    format!("__jx_{command}")
}
