use super::*;

/// Supported shell targets for generated integration scripts.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum ShellKind {
    Bash,
}

/// Renders shell integration that wires configured navigation and completion into the shell.
pub(super) fn shell_init_script(shell: ShellKind, config: &ShellConfig) -> String {
    match shell {
        ShellKind::Bash => bash_init_script(config),
    }
}

fn bash_init_script(config: &ShellConfig) -> String {
    let mut script = bash_cli_completion_script();

    if let Some(command) = config.navigation_command() {
        if !script.ends_with('\n') {
            script.push('\n');
        }
        script.push('\n');
        script.push_str(&bash_navigation_script(
            command,
            config.navigation_tab_command(),
            config.zoxide,
        ));
    }

    script
}

fn bash_cli_completion_script() -> String {
    let mut command = cli();
    let mut output = Vec::new();
    clap_complete::generate(clap_complete::Shell::Bash, &mut command, "jx", &mut output);
    let mut script = String::from_utf8(output).expect("clap_complete emits valid UTF-8");
    script.push_str(bash_project_argument_completion_script());
    script.push_str(&bash_work_cd_script());
    script
}

fn bash_project_argument_completion_script() -> &'static str {
    r#"
# Generated by jx shell init bash: project argument completion.
__jx_work_delete_completion() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local word
  local positional_count=0

  if [[ "$cur" == -* ]]; then
    _jx "$@"
    return
  fi

  for (( i = 3; i < COMP_CWORD; i++ )); do
    word="${COMP_WORDS[i]}"
    [[ "$word" == -* ]] && continue
    (( positional_count++ ))
  done

  if (( positional_count > 0 )); then
    COMPREPLY=()
    return
  fi

  local IFS=$'\n'
  COMPREPLY=($(compgen -W "$(command jx work complete --workspaces --prefix "$cur" 2>/dev/null)" -- "$cur"))
}

__jx_project_arg_completion() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local command=""
  local previous=""
  local word
  local positional_count=0
  local all_selected=0

  if [[ "${COMP_WORDS[1]}" == "work" && "${COMP_WORDS[2]}" == "delete" ]]; then
    __jx_work_delete_completion "$@"
    return
  fi

  for (( i = 1; i < COMP_CWORD; i++ )); do
    word="${COMP_WORDS[i]}"
    if [[ -z "$command" ]]; then
      case "$word" in
        remote-status|rs|fetch|f|sync|open|o) command="$word" ;;
      esac
      continue
    fi

    case "$previous" in
      --repo)
        previous=""
        (( positional_count++ ))
        continue
        ;;
      --jobs|-j)
        previous=""
        continue
        ;;
    esac

    case "$word" in
      -a|--all) [[ "$command" != "open" && "$command" != "o" ]] && all_selected=1 ;;
      --repo=*|--jobs=*) ;;
      -*) previous="$word" ;;
      pr|pull-request)
        (( positional_count++ ))
        ;;
      prs|pull-requests)
        if [[ ( "$command" == "open" || "$command" == "o" ) && $positional_count -eq 0 ]]; then
          :
        else
          (( positional_count++ ))
        fi
        ;;
      *) (( positional_count++ )) ;;
    esac
  done

  case "$previous" in
    --repo)
      local IFS=$'\n'
      COMPREPLY=($(compgen -W "$(command jx work complete --repositories --prefix "$cur" 2>/dev/null)" -- "$cur"))
      return
      ;;
    --jobs|-j)
      _jx "$@"
      return
      ;;
  esac

  if [[ -n "$command" && "$cur" != -* && $positional_count -eq 0 && $all_selected -eq 0 ]]; then
    local IFS=$'\n'
    COMPREPLY=($(compgen -W "$(command jx work complete --repositories --prefix "$cur" 2>/dev/null)" -- "$cur"))
  else
    _jx "$@"
  fi
}

complete -F __jx_project_arg_completion jx
"#
}

fn bash_work_cd_script() -> String {
    format!(
        r#"
# Generated by jx shell init bash: enter newly added workspaces, jump to trunk checkouts, and leave deleted ones safely.
jx() {{
  if [[ "$1" == "work" && ( "$2" == "add" || "$2" == "trunk" || "$2" == "delete" ) ]]; then
    local output status line cd_target=""
    output="$(command jx work "$2" --shell-cd-target "${{@:3}}")"
    status=$?
    if [[ -n "$output" ]]; then
      while IFS= read -r line; do
        case "$line" in
          {prefix}*) cd_target="${{line#{prefix}}}" ;;
          *) printf '%s\n' "$line" ;;
        esac
      done <<< "$output"
    fi
    if (( status == 0 )) && [[ -n "$cd_target" ]]; then
      if [[ "$2" == "delete" ]]; then
        cd "$cd_target"
      else
        pushd "$cd_target" > /dev/null
      fi
      status=$?
      (( status == 0 )) && dirs -v
    fi
    return $status
  fi

  command jx "$@"
}}
"#,
        prefix = SHELL_CD_TARGET_PREFIX,
    )
}

fn bash_navigation_script(
    command: &str,
    tab_command: Option<&str>,
    zoxide: ShellZoxideMode,
) -> String {
    let helper_prefix = helper_prefix(command);
    let zoxide_enabled_function = bash_navigation_zoxide_enabled_function(&helper_prefix, zoxide);
    let jx_first_key_function = bash_navigation_jx_first_key_function(&helper_prefix, zoxide);
    let zoxide_completion_function =
        bash_navigation_zoxide_completion_function(&helper_prefix, zoxide);
    let resolution = bash_navigation_resolution(&helper_prefix, zoxide);
    let prefer_completion = bash_navigation_prefer_completion(&helper_prefix, zoxide);
    let auto_zoxide_completion = bash_navigation_auto_zoxide_completion(&helper_prefix, zoxide);
    let tab_function = bash_navigation_tab_function(&helper_prefix, tab_command);
    let tab_case = tab_command
        .map(|_| format!("    tab) {helper_prefix}_tab \"$@\" ;;\n"))
        .unwrap_or_default();
    let command_functions = bash_navigation_command_functions(&helper_prefix, command, tab_command);
    let completion_commands = tab_command.map_or_else(
        || command.to_owned(),
        |tab_command| format!("{command} {tab_command}"),
    );

    format!(
        r#"# Generated by jx shell init bash.
{zoxide_enabled_function}{jx_first_key_function}{helper_prefix}_path_like() {{
  [[ "$1" == /* || "$1" == "." || "$1" == ".." || "$1" == ./* || "$1" == ../* ]]
}}

{helper_prefix}_cd() {{
  local ret
  pushd "$@" > /dev/null
  ret=$?
  (( ret == 0 )) && dirs -v
  return $ret
}}
{tab_function}
{helper_prefix}_navigate() {{
  local mode="$1"
  shift
  case "$mode" in
    cd) {helper_prefix}_cd "$@" ;;
{tab_case}    *) return 2 ;;
  esac
}}

{helper_prefix}_resolve_and_navigate() {{
  local mode="$1"
  shift
  local target

  if (( $# == 0 )); then
    target="$HOME"
  elif (( $# == 1 )) && {helper_prefix}_path_like "$1"; then
    {helper_prefix}_navigate "$mode" "$1"
    return $?
{resolution}  else
    {helper_prefix}_navigate "$mode" "$@"
    return $?
  fi

  {helper_prefix}_navigate "$mode" "$target"
}}

{command_functions}
{helper_prefix}_completion_cache_key=
{helper_prefix}_completion_cache_time=0
{helper_prefix}_completion_cache=

{helper_prefix}_jx_completion_candidates() {{
  local now
  now="$(date +%s 2>/dev/null)" || now=0
  if [[ "${{{helper_prefix}_completion_cache_key}}" != "$PWD" || $(( now - {helper_prefix}_completion_cache_time )) -ge 30 ]]; then
    {helper_prefix}_completion_cache="$(command jx work complete --navigation --prefix "" 2>/dev/null)"
    {helper_prefix}_completion_cache_key="$PWD"
    {helper_prefix}_completion_cache_time="$now"
  fi
  printf '%s\n' "${{{helper_prefix}_completion_cache}}"
}}

{helper_prefix}_add_candidate() {{
  local candidate="$1" existing
  [[ -n "$candidate" ]] || return 0
  for existing in "${{candidates[@]}}"; do
    [[ "$existing" == "$candidate" ]] && return 0
  done
  candidates+=("$candidate")
}}
{zoxide_completion_function}
{helper_prefix}_completion() {{
  local cur="${{COMP_WORDS[COMP_CWORD]}}"
  local IFS=$'\n'
  local candidates=()
  local candidate path

  if {helper_prefix}_path_like "$cur"; then
    compopt -o filenames 2>/dev/null || true
    COMPREPLY=($(compgen -d -- "$cur"))
    return
  fi
{prefer_completion}
  while IFS= read -r candidate; do
    [[ -n "$candidate" && "$candidate" == "$cur"* ]] && {helper_prefix}_add_candidate "$candidate"
  done < <({helper_prefix}_jx_completion_candidates)
{auto_zoxide_completion}
  COMPREPLY=($(compgen -W "${{candidates[*]}}" -- "$cur"))
}}

complete -o nospace -F {helper_prefix}_completion {completion_commands}
"#
    )
}

fn bash_navigation_zoxide_enabled_function(helper_prefix: &str, zoxide: ShellZoxideMode) -> String {
    match zoxide {
        ShellZoxideMode::Auto | ShellZoxideMode::Prefer => format!(
            r#"{helper_prefix}_zoxide_enabled() {{
  command -v zoxide >/dev/null 2>&1
}}

"#
        ),
        ShellZoxideMode::Never => String::new(),
    }
}

fn bash_navigation_jx_first_key_function(helper_prefix: &str, zoxide: ShellZoxideMode) -> String {
    match zoxide {
        ShellZoxideMode::Prefer => format!(
            r#"{helper_prefix}_jx_first_key() {{
  [[ "$1" == "default" || "$1" == "trunk" || "$1" == "root" ]]
}}

"#
        ),
        ShellZoxideMode::Auto | ShellZoxideMode::Never => String::new(),
    }
}

fn bash_navigation_resolution(helper_prefix: &str, zoxide: ShellZoxideMode) -> String {
    match zoxide {
        ShellZoxideMode::Auto => format!(
            r#"  elif (( $# == 1 )) && target="$(command jx work root --navigation "$1" 2>/dev/null)"; then
    :
  elif {helper_prefix}_zoxide_enabled && target="$(zoxide query "$@" 2>/dev/null)"; then
    :
"#
        ),
        ShellZoxideMode::Never => r#"  elif (( $# == 1 )) && target="$(command jx work root --navigation "$1" 2>/dev/null)"; then
    :
"#
        .to_owned(),
        ShellZoxideMode::Prefer => format!(
            r#"  elif (( $# == 1 )) && {helper_prefix}_jx_first_key "$1" && target="$(command jx work root --navigation "$1" 2>/dev/null)"; then
    :
  elif {helper_prefix}_zoxide_enabled && target="$(zoxide query "$@" 2>/dev/null)"; then
    :
  elif (( $# == 1 )) && target="$(command jx work root --navigation "$1" 2>/dev/null)"; then
    :
"#
        ),
    }
}

fn bash_navigation_zoxide_completion_function(
    helper_prefix: &str,
    zoxide: ShellZoxideMode,
) -> String {
    match zoxide {
        ShellZoxideMode::Auto | ShellZoxideMode::Prefer => format!(
            r#"
{helper_prefix}_add_zoxide_candidates() {{
  {helper_prefix}_zoxide_enabled || return 0
  while IFS= read -r path; do
    candidate="$(basename "$path")"
    {helper_prefix}_add_candidate "$candidate"
  done < <(zoxide query --list "$1" 2>/dev/null)
}}
"#
        ),
        ShellZoxideMode::Never => String::new(),
    }
}

fn bash_navigation_prefer_completion(helper_prefix: &str, zoxide: ShellZoxideMode) -> String {
    match zoxide {
        ShellZoxideMode::Prefer => format!(
            r#"
  if [[ -n "$cur" ]]; then
    for candidate in default trunk root; do
      [[ "$candidate" == "$cur"* ]] && {helper_prefix}_add_candidate "$candidate"
    done
  fi
  {helper_prefix}_add_zoxide_candidates "$cur"
  if (( ${{#candidates[@]}} > 0 )); then
    COMPREPLY=($(compgen -W "${{candidates[*]}}" -- "$cur"))
    return
  fi
"#
        ),
        ShellZoxideMode::Auto | ShellZoxideMode::Never => String::new(),
    }
}

fn bash_navigation_auto_zoxide_completion(helper_prefix: &str, zoxide: ShellZoxideMode) -> String {
    match zoxide {
        ShellZoxideMode::Auto => format!(
            r#"
  {helper_prefix}_add_zoxide_candidates "$cur"
"#
        ),
        ShellZoxideMode::Never | ShellZoxideMode::Prefer => String::new(),
    }
}

fn bash_navigation_tab_function(helper_prefix: &str, tab_command: Option<&str>) -> String {
    if tab_command.is_none() {
        return String::new();
    }

    format!(
        r#"
{helper_prefix}_tab() {{
  if (( $# != 1 )); then
    printf 'jx: opening tabs requires one resolved directory; entering directory instead\n' >&2
    {helper_prefix}_cd "$@"
    return $?
  fi

  if [[ -n "${{ZELLIJ:-}}" ]]; then
    zellij action new-tab --cwd "$1" >/dev/null
    return $?
  fi

  printf 'jx: opening tabs is only supported inside zellij; entering directory instead\n' >&2
  {helper_prefix}_cd "$1"
}}
"#
    )
}

fn bash_navigation_command_functions(
    helper_prefix: &str,
    command: &str,
    tab_command: Option<&str>,
) -> String {
    let mut functions = format!(
        r#"{command}() {{
  {helper_prefix}_resolve_and_navigate cd "$@"
}}
"#
    );
    if let Some(tab_command) = tab_command {
        functions.push_str(&format!(
            r#"
{tab_command}() {{
  {helper_prefix}_resolve_and_navigate tab "$@"
}}
"#
        ));
    }
    functions
}

fn helper_prefix(command: &str) -> String {
    format!("__jx_{command}")
}
